name: Build Windows Executable

on:
  push:
    branches:
      - main
  # Trigger the workflow on tag creation
  release:
    types:
      - created

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify the desired Python version

      - name: Install pipenv and dependencies
        run: |
          pip install pipenv
          pipenv install --dev  # Add --deploy if you want to ignore development dependencies

      - name: Build Windows Executable
        run: |
          # Install PyInstaller (if not already installed)
          pipenv run pip install pyinstaller

          # Generate the executable using PyInstaller
          pipenv run PyInstaller  main.spec
        # Replace 'myapp.spec' with the name of your spec file.

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Executable
          path: ./dist/

      # If the event was a tag creation, create a GitHub release
      - name: Create Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*
          tag_name: ${{ github.ref }}
          body: ${{ github.event.release.body }}
